version: '3.7'

services:
  project:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/project/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #Don't use secret data in environment in production
    environment:
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_DB=projectdb
  
volumes:
  postgres_data:
