# Generated by Django 3.0.7 on 2020-10-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20201012_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
