# Generated by Django 3.0.7 on 2020-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201008_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'published'), ('UPDATED', 'updated')], default='published', max_length=15),
        ),
    ]
